# описания сервисов (контейнеров), которые должны быть развёрнуты
services:
  # описание контейнера db
  db: # имя сервиса
    # образ, из которого должен быть запущен контейнер
    image: postgres:16.1
    # имя, которое нужно присвоить контейнеру
    container_name: postgres
    # публикуемые порты
    ports:
      - "5432:5432"
    # настройки монтирования volume
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    # переменные окружения
    environment:
      - POSTGRES_DB=shareddb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword